spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/indiagator/skillwise-config-properties.git
server:
    port: 8071
